---
abstract: 'CGI utility suite - makes powerful application writing fun and easy'
author:
  - 'Paul Seamons'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Ex
no_index:
  directory:
    - t
    - inc
requires:
  Template::Alloy: 1.016
version: 2.42
