--- #YAML:1.0
name:                CGI-Ex
version:             2.32
abstract:            CGI utility suite - makes powerful application writing fun and easy
license:             ~
author:              
    - Paul Seamons
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Template::Alloy:               1.004
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
